version: "3.9"
services:
  web:
    build: .
    restart: always
    networks:
      - db
    volumes:
      - ./app:/code
      - ./data:/data
  mysql:
    image: "mysql/mysql-server:latest"
    restart: always
    networks:
      - db
    cap_add:
      - SYS_NICE
    # This .env file below is used for MySQL config, and is different from env file!
    env_file:
      - ./app/.env
    expose:
      - '3306'
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d/1.sql
      - ./db:/var/lib/mysql
networks:
  db:



