#!/bin/bash

npm install
node app.js 8000 &
node app.js 8001 &
node app.js 8002 &
node app.js 8003 &
node app.js 8004 &
node app.js 8005 &
node app.js 8006 &
node app.js 8007 &

node app.js 8008 &
node app.js 8009 &
node app.js 8010 &
node app.js 8011 &
node app.js 8012 &
node app.js 8013 &
node app.js 8014 &
node app.js 8015 &
